name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: libsodium
        run: sudo apt-get update && sudo apt-get install -y libsodium-dev

      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get

      # format --check-formatted, credo --strict, compile
      # --warnings-as-errors, test
      - run: mix precommit
